### ISSUE TITLE
Looking up every k-mer in reads

### ISSUE THREAD

**Issue by mohsenzakeri** [jermp/sshash-lite#1]
Dear @jermp ,

I hope you're doing well.  I wanted to conduct a benchmark with `sshash-lite` for looking-up every k-mer in the reads without breaking the process based on the threshold value.  Essentially, I wanted to replicate the behavior of `sshash` which searches every k-mer by default.

To achieve this, I added a new flag, `every-kmer`, which you can review here:
https://github.com/mohsenzakeri/sshash-lite/commit/433369a844f5bec583fe6fbce747bf9b1d256b5f

This flag enforces the intended behavior by:
1. Setting the threshold to 1.
2. Preventing the loop from breaking based on the number of negative k-mers encountered.

I’d appreciate it if you could let me know whether you approve of this approach or if you have suggestions for an alternative method.

Best,
Mohsen

**Comment by jermp** [comment]
Hi @mohsenzakeri and sorry for the late reply (but, as you can imagine, these are very busy days near the end of the semester and year!).

Your changes look fine. Just to be sure we're on the same page: the difference between this behaviour and that of SSHash is that this one will just answer membership queries (and will not re-init the state of iterators when streaming to the first occurrence of a kmer), whereas SSHash will return a unique-id for a found kmer.

Let me know if I can assist you futher.

Cheers,
-Giulio

**Comment by jermp** [comment]
@mohsenzakeri
Closing this for the moment, but feel free to drop me a line at giulioermanno.pibiri@unive.it :)

**Comment by mohsenzakeri** [comment]
Thank you for your response.  You right, the behavior I was looking for is looking up k-mers in a streaming manner without generating the unique k-mer IDs.

Happy holidays!
Mohsen
